#!/usr/bin/env python3
"""
Expands verif/testlists/smoke.yaml's directed tests plus seeded sweeps of
every `kind: random` test in verif/testlists/standalone.yaml into
verif/testlists/daily.yaml (~100 tests: every directed/error/integration
test once, padded out with random-seed sweeps) and
verif/testlists/random.yaml (~100 tests: pure random-seed sweep, no
directed tests at all).

Both output files are GENERATED, not hand-edited -- same "YAML source of
truth + generator" convention as docs/register_map/tpe_regs.yaml +
tools/regmap_gen.py. Every seed across both tiers is distinct (seeds walk
upward from --seed-base), so any daily/random regression failure is
reproducible with a single standalone re-run:
    TESTCASE=<test> TPE_SEED=<seed> make -C verif/cocotb_tb/<dir>
"""
import argparse
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
TESTLIST_DIR = REPO_ROOT / "verif" / "testlists"

HEADER = (
    "# GENERATED by tools/gen_tests.py from verif/testlists/standalone.yaml +\n"
    "# verif/testlists/smoke.yaml -- do not hand-edit, run `make gen-tests`.\n"
)


def load(name):
    with open(TESTLIST_DIR / name) as f:
        return yaml.safe_load(f)


def random_capable_tests(catalog):
    tests = [t for t in catalog["tests"] if t.get("kind") == "random"]
    return sorted(tests, key=lambda t: (t["dir"], t["test"]))


def sweep(tests, count, seed_base):
    """Round-robins `count` (dir, test, seed) entries across the given
    random-capable tests, seeds walking upward from seed_base so every
    entry is distinct and reproducible."""
    out = []
    seed = seed_base
    i = 0
    while len(out) < count:
        t = tests[i % len(tests)]
        out.append({"dir": t["dir"], "test": t["test"], "seed": seed})
        seed += 1
        i += 1
    return out


def write(path, suite, tests):
    with open(path, "w") as f:
        f.write(HEADER)
        yaml.safe_dump({"suite": suite, "tests": tests}, f, sort_keys=False)
    print(f"gen_tests: wrote {path} ({len(tests)} tests)")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--daily-size", type=int, default=100)
    ap.add_argument("--random-size", type=int, default=100)
    ap.add_argument("--seed-base", type=int, default=10000)
    args = ap.parse_args()

    catalog = load("standalone.yaml")
    smoke = load("smoke.yaml")
    rnd_tests = random_capable_tests(catalog)
    if not rnd_tests:
        print("gen_tests: no `kind: random` entries in standalone.yaml", file=sys.stderr)
        sys.exit(1)

    directed = [{"dir": t["dir"], "test": t["test"]} for t in smoke["tests"]]
    daily_random_count = max(args.daily_size - len(directed), 0)
    daily = directed + sweep(rnd_tests, daily_random_count, args.seed_base)
    write(TESTLIST_DIR / "daily.yaml", "daily", daily)

    random_tests = sweep(rnd_tests, args.random_size, args.seed_base + 100000)
    write(TESTLIST_DIR / "random.yaml", "random", random_tests)


if __name__ == "__main__":
    main()
